### ISSUE TITLE
[Bug] Crash when launching game.

### ISSUE THREAD

**Issue by seriousCoolness** [Adventurecraft-Awakening/AC-Legacy-Mod#39]
When I try to press the play button on the new version, it loads for a bit, and then crashes with this error:

```
Uncaught exception in thread "main"
net.fabricmc.loader.impl.util.ExceptionUtil$WrappedException: java.io.IOException: error reading C:\Users\wyatt\AppData\Roaming\adventurecraft-launcher\GameFiles\mc173\minecraft\libraries\com\google\guava\guava\31.0.1-jre\guava-31.0.1-jre.jar
	at net.fabricmc.loader.impl.util.ExceptionUtil.wrap(ExceptionUtil.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.locateGame(MinecraftGameProvider.java:232)
	at net.fabricmc.loader.impl.launch.knot.Knot.createGameProvider(Knot.java:177)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:130)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.io.IOException: error reading C:\Users\wyatt\AppData\Roaming\adventurecraft-launcher\GameFiles\mc173\minecraft\libraries\com\google\guava\guava\31.0.1-jre\guava-31.0.1-jre.jar
	at net.fabricmc.loader.impl.game.LibClassifier.process(LibClassifier.java:216)
	at net.fabricmc.loader.impl.game.LibClassifier.process(LibClassifier.java:163)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.locateGame(MinecraftGameProvider.java:187)
	... 4 more
Caused by: java.util.zip.ZipException: zip END header not found
	at java.base/java.util.zip.ZipFile$Source.findEND(Unknown Source)
	at java.base/java.util.zip.ZipFile$Source.initCEN(Unknown Source)
	at java.base/java.util.zip.ZipFile$Source.<init>(Unknown Source)
	at java.base/java.util.zip.ZipFile$Source.get(Unknown Source)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(Unknown Source)
	at java.base/java.util.zip.ZipFile.<init>(Unknown Source)
	at java.base/java.util.zip.ZipFile.<init>(Unknown Source)
	at java.base/java.util.zip.ZipFile.<init>(Unknown Source)
	at net.fabricmc.loader.impl.game.LibClassifier.process(LibClassifier.java:203)
	... 6 more

```

**Comment by TechPizzaDev** [comment]
Looks a bit like the game may have failed to download? Hard to tell.

**Comment by TechPizzaDev** [comment]
@seriousCoolness Can you try deleting that file and see if the launcher fetches it again?
